<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Transactions</name>
   <tag></tag>
   <elementGuidId>704aefa4-5ff0-49e7-8286-d7659a1cb92c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transactions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember496&quot;)/div[@class=&quot;padding-body&quot;]/div[@class=&quot;container padding-container&quot;]/div[@class=&quot;home-page-body top-my-kids&quot;]/div[@class=&quot;col-md-12 none-padding padding-leftRight-zero&quot;]/div[@class=&quot;margin-menu&quot;]/center[1]/h2[1]</value>
   </webElementProperties>
</WebElementEntity>
