<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nickname</name>
   <tag></tag>
   <elementGuidId>d33ee689-2721-4304-a33a-2f55bd3d3d7e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nickname</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember427&quot;)/div[@class=&quot;padding-body&quot;]/div[@class=&quot;container padding-container&quot;]/div[@class=&quot;home-page-body top-my-kids&quot;]/div[@class=&quot;col-md-12 none-padding padding-leftRight-zero&quot;]/div[@class=&quot;margin-content-menus padding-details-menus&quot;]/div[@class=&quot;col-md-8 col-sm-7 col-xs-12 padding-align-profile padding-leftRight-zero&quot;]/form[@class=&quot;label-title&quot;]/div[@class=&quot;col-md-12 col-xs-12 padding-content padding-leftRight-zero&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
