<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>efd0259f-45cb-4052-a51b-2e177b82aca9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn col-xs-5 login-cancel-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ember-action</name>
      <type>Main</type>
      <value>1349</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember573&quot;)/div[@class=&quot;padding-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col-md-12 col-xs-12 margins-container-login required-padding&quot;]/div[@class=&quot;div-right col-md-6 col-xs-12 padding-leftRight-zero&quot;]/form[@class=&quot;label-title login-form&quot;]/div[@class=&quot;col-xs-12 form-group&quot;]/button[@class=&quot;btn col-xs-5 login-cancel-button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
